<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Elogic\CustomerShoppingCart\Block\Onepage\ExportCartItems */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if ($block->isExportShoppingCartEnable()) :?>
    <a class="action"
       href="<?= $escaper->escapeUrl($block->getExportCartInCsvUrl()) ?>">
        <span><?= $escaper->escapeHtml(__($block::EXPORT_BUTTON_LABEL)) ?></span>
    </a>
<?php endif?>
